name: 'Get Next Version'
description: 'Gets next version based on previous tag'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  version_file:
    description: 'version file'
    required: true
    default: 'package.json'
outputs:
  tag:
    description: 'last tag version'
  version:
    description: 'next tag version'
runs:
  using: 'node12'
  main: 'dist/index.js'
